// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HostFilter.proto

package org.test.hbase;

public final class HostFilterProtos {
  private HostFilterProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface HostFilterOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 hostLimit = 1;
    /**
     * <code>optional int32 hostLimit = 1;</code>
     */
    boolean hasHostLimit();
    /**
     * <code>optional int32 hostLimit = 1;</code>
     */
    int getHostLimit();
  }
  /**
   * Protobuf type {@code HostFilter}
   */
  public static final class HostFilter extends
      com.google.protobuf.GeneratedMessage
      implements HostFilterOrBuilder {
    // Use HostFilter.newBuilder() to construct.
    private HostFilter(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private HostFilter(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final HostFilter defaultInstance;
    public static HostFilter getDefaultInstance() {
      return defaultInstance;
    }

    public HostFilter getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private HostFilter(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              hostLimit_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.test.hbase.HostFilterProtos.internal_static_HostFilter_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.test.hbase.HostFilterProtos.internal_static_HostFilter_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.test.hbase.HostFilterProtos.HostFilter.class, org.test.hbase.HostFilterProtos.HostFilter.Builder.class);
    }

    public static com.google.protobuf.Parser<HostFilter> PARSER =
        new com.google.protobuf.AbstractParser<HostFilter>() {
      public HostFilter parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HostFilter(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<HostFilter> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 hostLimit = 1;
    public static final int HOSTLIMIT_FIELD_NUMBER = 1;
    private int hostLimit_;
    /**
     * <code>optional int32 hostLimit = 1;</code>
     */
    public boolean hasHostLimit() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 hostLimit = 1;</code>
     */
    public int getHostLimit() {
      return hostLimit_;
    }

    private void initFields() {
      hostLimit_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, hostLimit_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, hostLimit_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.test.hbase.HostFilterProtos.HostFilter)) {
        return super.equals(obj);
      }
      org.test.hbase.HostFilterProtos.HostFilter other = (org.test.hbase.HostFilterProtos.HostFilter) obj;

      boolean result = true;
      result = result && (hasHostLimit() == other.hasHostLimit());
      if (hasHostLimit()) {
        result = result && (getHostLimit()
            == other.getHostLimit());
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasHostLimit()) {
        hash = (37 * hash) + HOSTLIMIT_FIELD_NUMBER;
        hash = (53 * hash) + getHostLimit();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.test.hbase.HostFilterProtos.HostFilter parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.test.hbase.HostFilterProtos.HostFilter parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.test.hbase.HostFilterProtos.HostFilter parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.test.hbase.HostFilterProtos.HostFilter parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.test.hbase.HostFilterProtos.HostFilter parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.test.hbase.HostFilterProtos.HostFilter parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.test.hbase.HostFilterProtos.HostFilter parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.test.hbase.HostFilterProtos.HostFilter parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.test.hbase.HostFilterProtos.HostFilter parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.test.hbase.HostFilterProtos.HostFilter parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.test.hbase.HostFilterProtos.HostFilter prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HostFilter}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.test.hbase.HostFilterProtos.HostFilterOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.test.hbase.HostFilterProtos.internal_static_HostFilter_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.test.hbase.HostFilterProtos.internal_static_HostFilter_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.test.hbase.HostFilterProtos.HostFilter.class, org.test.hbase.HostFilterProtos.HostFilter.Builder.class);
      }

      // Construct using org.test.hbase.HostFilterProtos.HostFilter.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        hostLimit_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.test.hbase.HostFilterProtos.internal_static_HostFilter_descriptor;
      }

      public org.test.hbase.HostFilterProtos.HostFilter getDefaultInstanceForType() {
        return org.test.hbase.HostFilterProtos.HostFilter.getDefaultInstance();
      }

      public org.test.hbase.HostFilterProtos.HostFilter build() {
        org.test.hbase.HostFilterProtos.HostFilter result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.test.hbase.HostFilterProtos.HostFilter buildPartial() {
        org.test.hbase.HostFilterProtos.HostFilter result = new org.test.hbase.HostFilterProtos.HostFilter(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.hostLimit_ = hostLimit_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.test.hbase.HostFilterProtos.HostFilter) {
          return mergeFrom((org.test.hbase.HostFilterProtos.HostFilter)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.test.hbase.HostFilterProtos.HostFilter other) {
        if (other == org.test.hbase.HostFilterProtos.HostFilter.getDefaultInstance()) return this;
        if (other.hasHostLimit()) {
          setHostLimit(other.getHostLimit());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.test.hbase.HostFilterProtos.HostFilter parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.test.hbase.HostFilterProtos.HostFilter) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 hostLimit = 1;
      private int hostLimit_ ;
      /**
       * <code>optional int32 hostLimit = 1;</code>
       */
      public boolean hasHostLimit() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 hostLimit = 1;</code>
       */
      public int getHostLimit() {
        return hostLimit_;
      }
      /**
       * <code>optional int32 hostLimit = 1;</code>
       */
      public Builder setHostLimit(int value) {
        bitField0_ |= 0x00000001;
        hostLimit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 hostLimit = 1;</code>
       */
      public Builder clearHostLimit() {
        bitField0_ = (bitField0_ & ~0x00000001);
        hostLimit_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:HostFilter)
    }

    static {
      defaultInstance = new HostFilter(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:HostFilter)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_HostFilter_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_HostFilter_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020HostFilter.proto\"\037\n\nHostFilter\022\021\n\thost" +
      "Limit\030\001 \001(\005B*\n\016org.test.hbaseB\020HostFilte" +
      "rProtosH\001\210\001\001\240\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_HostFilter_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_HostFilter_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_HostFilter_descriptor,
              new java.lang.String[] { "HostLimit", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
